import HamburgerMenu from '@/src/components/hamburger-menu';
import type { Metadata } from 'next';
import { IBM_Plex_Mono, IBM_Plex_Sans } from 'next/font/google';
import BackButton from '../components/back-button';
import './globals.css';
import { Providers } from './providers';

const ibmPlexSans = IBM_Plex_Sans({
  variable: '--font-ibm-plex-sans',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

const ibmPlexMono = IBM_Plex_Mono({
  variable: '--font-ibm-plex-mono',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${ibmPlexMono.variable} ${ibmPlexSans.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <HamburgerMenu />
          <BackButton
            fallbackHref="/"
            className={[
              'fixed top-3 left-15 z-50 flex items-center justify-center gap-2 px-2 py-5 rounded-lg border ',
              'transition-all duration-1000 ease-[cubic-bezier(0.16,1,0.3,1)]',
              'border-black/8 bg-white dark:border-white/8 dark:bg-black',
              'backdrop-blur-[50px]',
              'shadow-[inset_0_1px_0_rgba(0,0,0,0.06),0_2px_16px_rgba(100,100,100,0.18)]',
              'dark:shadow-[inset_0_1px_0_rgba(255,255,255,0.25),0_2px_16px_rgba(175,175,175,0.25)]',
              'hover:border-black/25 hover:bg-white/40 dark:hover:border-white/25 dark:hover:bg-black/40',
              'hover:shadow-[inset_0_1px_0_rgba(0,0,0,0.10),0_2px_16px_rgba(100,100,100,0.30)]',
              'dark:hover:shadow-[inset_0_1px_0_rgba(255,255,255,0.35),0_2px_16px_rgba(175,175,175,0.35)]',
            ].join(' ')}
          />
          {children}
        </Providers>
      </body>
    </html>
  );
}
