FROM rust:1.95.0-slim-bullseye AS builder
WORKDIR /usr/src/app

COPY Cargo.toml Cargo.lock build.rs ./
COPY --from=protos . ../proto

RUN mkdir src && echo "fn main() {}" > src/main.rs
RUN apt-get update && apt-get install -y curl && apt-get install -y protobuf-compiler
RUN cargo build
RUN rm src/main.rs

COPY src ./src
RUN touch src/main.rs
RUN cargo build

FROM debian:bullseye-slim

WORKDIR /app

RUN apt-get update && \
  apt-get install -y libpq-dev ca-certificates && \
  rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/src/app/target/debug/api_gateway /usr/local/bin/server

EXPOSE 3000

CMD ["server"]
