version: "3"

tasks:
   proto-gen:
      desc: Generate gRPC stubs from proto files
      cmds:
         - protoc -I pkg/protos --experimental_allow_proto3_optional --go_out=. --go_opt=module=github.com/erickoda/build-a-computer/pc_builder_service --go-grpc_out=. --go-grpc_opt=module=github.com/erickoda/build-a-computer/pc_builder_service pkg/protos/*.proto