syntax = "proto3";

package pkg.protos.v1;

option go_package = "github.com/erickoda/build-a-computer/pc_builder_service/pkg/protos";

import "google/protobuf/timestamp.proto";

message Benchmark {
    string id = 1;
    string title = 2;
    int32 resolution = 3;
    string graphics_quality = 4;

    string cpu_id = 5;
    string gpu_id = 6;
    string ram_id = 7;

    int32 avg_fps = 8;
    int32 min_fps = 9;
    int32 max_fps = 10;

    string game_id = 11;
    string user_id = 12;
    optional float score = 13;

    google.protobuf.Timestamp created_at = 14;
    optional google.protobuf.Timestamp updated_at = 15;
}
