// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: builder.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuildPCRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Games               []string               `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	MaxPrice            float32                `protobuf:"fixed32,2,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	Resolution          int32                  `protobuf:"varint,3,opt,name=resolution,proto3" json:"resolution,omitempty"`
	ComputerPerformance string                 `protobuf:"bytes,4,opt,name=computer_performance,json=computerPerformance,proto3" json:"computer_performance,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BuildPCRequest) Reset() {
	*x = BuildPCRequest{}
	mi := &file_builder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildPCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildPCRequest) ProtoMessage() {}

func (x *BuildPCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_builder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildPCRequest.ProtoReflect.Descriptor instead.
func (*BuildPCRequest) Descriptor() ([]byte, []int) {
	return file_builder_proto_rawDescGZIP(), []int{0}
}

func (x *BuildPCRequest) GetGames() []string {
	if x != nil {
		return x.Games
	}
	return nil
}

func (x *BuildPCRequest) GetMaxPrice() float32 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *BuildPCRequest) GetResolution() int32 {
	if x != nil {
		return x.Resolution
	}
	return 0
}

func (x *BuildPCRequest) GetComputerPerformance() string {
	if x != nil {
		return x.ComputerPerformance
	}
	return ""
}

type BuildPCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pc            []*PC                  `protobuf:"bytes,1,rep,name=pc,proto3" json:"pc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildPCResponse) Reset() {
	*x = BuildPCResponse{}
	mi := &file_builder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildPCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildPCResponse) ProtoMessage() {}

func (x *BuildPCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_builder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildPCResponse.ProtoReflect.Descriptor instead.
func (*BuildPCResponse) Descriptor() ([]byte, []int) {
	return file_builder_proto_rawDescGZIP(), []int{1}
}

func (x *BuildPCResponse) GetPc() []*PC {
	if x != nil {
		return x.Pc
	}
	return nil
}

type PC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           *CPU                   `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Gpu           *GPU                   `protobuf:"bytes,2,opt,name=gpu,proto3" json:"gpu,omitempty"`
	Ram           *RAMMemory             `protobuf:"bytes,3,opt,name=ram,proto3" json:"ram,omitempty"`
	MotherBoard   *MotherBoard           `protobuf:"bytes,4,opt,name=mother_board,json=motherBoard,proto3" json:"mother_board,omitempty"`
	Psu           *PowerSource           `protobuf:"bytes,5,opt,name=psu,proto3" json:"psu,omitempty"`
	Ssd           *SSD                   `protobuf:"bytes,6,opt,name=ssd,proto3" json:"ssd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PC) Reset() {
	*x = PC{}
	mi := &file_builder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PC) ProtoMessage() {}

func (x *PC) ProtoReflect() protoreflect.Message {
	mi := &file_builder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PC.ProtoReflect.Descriptor instead.
func (*PC) Descriptor() ([]byte, []int) {
	return file_builder_proto_rawDescGZIP(), []int{2}
}

func (x *PC) GetCpu() *CPU {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *PC) GetGpu() *GPU {
	if x != nil {
		return x.Gpu
	}
	return nil
}

func (x *PC) GetRam() *RAMMemory {
	if x != nil {
		return x.Ram
	}
	return nil
}

func (x *PC) GetMotherBoard() *MotherBoard {
	if x != nil {
		return x.MotherBoard
	}
	return nil
}

func (x *PC) GetPsu() *PowerSource {
	if x != nil {
		return x.Psu
	}
	return nil
}

func (x *PC) GetSsd() *SSD {
	if x != nil {
		return x.Ssd
	}
	return nil
}

var File_builder_proto protoreflect.FileDescriptor

const file_builder_proto_rawDesc = "" +
	"\n" +
	"\rbuilder.proto\x12\x11recommendation.v1\x1a\x0fhardwares.proto\"\x96\x01\n" +
	"\x0eBuildPCRequest\x12\x14\n" +
	"\x05games\x18\x01 \x03(\tR\x05games\x12\x1b\n" +
	"\tmax_price\x18\x02 \x01(\x02R\bmaxPrice\x12\x1e\n" +
	"\n" +
	"resolution\x18\x03 \x01(\x05R\n" +
	"resolution\x121\n" +
	"\x14computer_performance\x18\x04 \x01(\tR\x13computerPerformance\"8\n" +
	"\x0fBuildPCResponse\x12%\n" +
	"\x02pc\x18\x01 \x03(\v2\x15.recommendation.v1.PCR\x02pc\"\xa7\x02\n" +
	"\x02PC\x12(\n" +
	"\x03cpu\x18\x01 \x01(\v2\x16.recommendation.v1.CPUR\x03cpu\x12(\n" +
	"\x03gpu\x18\x02 \x01(\v2\x16.recommendation.v1.GPUR\x03gpu\x12.\n" +
	"\x03ram\x18\x03 \x01(\v2\x1c.recommendation.v1.RAMMemoryR\x03ram\x12A\n" +
	"\fmother_board\x18\x04 \x01(\v2\x1e.recommendation.v1.MotherBoardR\vmotherBoard\x120\n" +
	"\x03psu\x18\x05 \x01(\v2\x1e.recommendation.v1.PowerSourceR\x03psu\x12(\n" +
	"\x03ssd\x18\x06 \x01(\v2\x16.recommendation.v1.SSDR\x03ssd2b\n" +
	"\x0eBuilderService\x12P\n" +
	"\aBuildPC\x12!.recommendation.v1.BuildPCRequest\x1a\".recommendation.v1.BuildPCResponseBDZBgithub.com/erickoda/build-a-computer/pc_builder_service/pkg/protosb\x06proto3"

var (
	file_builder_proto_rawDescOnce sync.Once
	file_builder_proto_rawDescData []byte
)

func file_builder_proto_rawDescGZIP() []byte {
	file_builder_proto_rawDescOnce.Do(func() {
		file_builder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_builder_proto_rawDesc), len(file_builder_proto_rawDesc)))
	})
	return file_builder_proto_rawDescData
}

var file_builder_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_builder_proto_goTypes = []any{
	(*BuildPCRequest)(nil),  // 0: recommendation.v1.BuildPCRequest
	(*BuildPCResponse)(nil), // 1: recommendation.v1.BuildPCResponse
	(*PC)(nil),              // 2: recommendation.v1.PC
	(*CPU)(nil),             // 3: recommendation.v1.CPU
	(*GPU)(nil),             // 4: recommendation.v1.GPU
	(*RAMMemory)(nil),       // 5: recommendation.v1.RAMMemory
	(*MotherBoard)(nil),     // 6: recommendation.v1.MotherBoard
	(*PowerSource)(nil),     // 7: recommendation.v1.PowerSource
	(*SSD)(nil),             // 8: recommendation.v1.SSD
}
var file_builder_proto_depIdxs = []int32{
	2, // 0: recommendation.v1.BuildPCResponse.pc:type_name -> recommendation.v1.PC
	3, // 1: recommendation.v1.PC.cpu:type_name -> recommendation.v1.CPU
	4, // 2: recommendation.v1.PC.gpu:type_name -> recommendation.v1.GPU
	5, // 3: recommendation.v1.PC.ram:type_name -> recommendation.v1.RAMMemory
	6, // 4: recommendation.v1.PC.mother_board:type_name -> recommendation.v1.MotherBoard
	7, // 5: recommendation.v1.PC.psu:type_name -> recommendation.v1.PowerSource
	8, // 6: recommendation.v1.PC.ssd:type_name -> recommendation.v1.SSD
	0, // 7: recommendation.v1.BuilderService.BuildPC:input_type -> recommendation.v1.BuildPCRequest
	1, // 8: recommendation.v1.BuilderService.BuildPC:output_type -> recommendation.v1.BuildPCResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_builder_proto_init() }
func file_builder_proto_init() {
	if File_builder_proto != nil {
		return
	}
	file_hardwares_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_builder_proto_rawDesc), len(file_builder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_builder_proto_goTypes,
		DependencyIndexes: file_builder_proto_depIdxs,
		MessageInfos:      file_builder_proto_msgTypes,
	}.Build()
	File_builder_proto = out.File
	file_builder_proto_goTypes = nil
	file_builder_proto_depIdxs = nil
}
