syntax = "proto3";

package pkg.proto;

import "hardwares.proto";

option go_package = "github.com/erickoda/build-a-computer/pc_builder_service/pkg/protos";

enum ComputerPerformance {
  COMPUTER_PERFORMANCE_LOW_UNSPECIFIED = 0;
  COMPUTER_PERFORMANCE_MEDIUM = 1;
  COMPUTER_PERFORMANCE_HIGH = 2;
}

message BuildPCRequest {
  repeated string games = 1;
  float max_price = 2;
  int32 resolution = 3;
  ComputerPerformance computer_performance = 4;
}

message BuildPCResponse {
  repeated PC pc = 1;
}

message PC {
  CPU cpu = 1;
  GPU gpu = 2;
  RAMMemory ram = 3;
  MotherBoard mother_board = 4;
  PowerSource psu = 5;
}

service BuilderService {
  rpc BuildPC(BuildPCRequest) returns (BuildPCResponse);
}
