// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: hardwares.proto

package protos

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CPU struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Brand            string                 `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	Gen              string                 `protobuf:"bytes,3,opt,name=gen,proto3" json:"gen,omitempty"`
	Cores            int32                  `protobuf:"varint,4,opt,name=cores,proto3" json:"cores,omitempty"`
	Threads          int32                  `protobuf:"varint,5,opt,name=threads,proto3" json:"threads,omitempty"`
	BaseClock        float32                `protobuf:"fixed32,6,opt,name=base_clock,json=baseClock,proto3" json:"base_clock,omitempty"`
	MaxClock         float32                `protobuf:"fixed32,7,opt,name=max_clock,json=maxClock,proto3" json:"max_clock,omitempty"`
	Cache            int32                  `protobuf:"varint,8,opt,name=cache,proto3" json:"cache,omitempty"`
	Socket           string                 `protobuf:"bytes,9,opt,name=socket,proto3" json:"socket,omitempty"`
	Graphics         bool                   `protobuf:"varint,10,opt,name=graphics,proto3" json:"graphics,omitempty"`
	Oc               bool                   `protobuf:"varint,11,opt,name=oc,proto3" json:"oc,omitempty"`
	RecommendedPower int32                  `protobuf:"varint,12,opt,name=recommended_power,json=recommendedPower,proto3" json:"recommended_power,omitempty"`
	AvgPrice         float32                `protobuf:"fixed32,13,opt,name=avg_price,json=avgPrice,proto3" json:"avg_price,omitempty"`
	ReleaseDate      *timestamp.Timestamp   `protobuf:"bytes,14,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	Img              []byte                 `protobuf:"bytes,15,opt,name=img,proto3,oneof" json:"img,omitempty"`
	CreatedAt        *timestamp.Timestamp   `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CPU) Reset() {
	*x = CPU{}
	mi := &file_hardwares_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPU) ProtoMessage() {}

func (x *CPU) ProtoReflect() protoreflect.Message {
	mi := &file_hardwares_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPU.ProtoReflect.Descriptor instead.
func (*CPU) Descriptor() ([]byte, []int) {
	return file_hardwares_proto_rawDescGZIP(), []int{0}
}

func (x *CPU) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CPU) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CPU) GetGen() string {
	if x != nil {
		return x.Gen
	}
	return ""
}

func (x *CPU) GetCores() int32 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *CPU) GetThreads() int32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

func (x *CPU) GetBaseClock() float32 {
	if x != nil {
		return x.BaseClock
	}
	return 0
}

func (x *CPU) GetMaxClock() float32 {
	if x != nil {
		return x.MaxClock
	}
	return 0
}

func (x *CPU) GetCache() int32 {
	if x != nil {
		return x.Cache
	}
	return 0
}

func (x *CPU) GetSocket() string {
	if x != nil {
		return x.Socket
	}
	return ""
}

func (x *CPU) GetGraphics() bool {
	if x != nil {
		return x.Graphics
	}
	return false
}

func (x *CPU) GetOc() bool {
	if x != nil {
		return x.Oc
	}
	return false
}

func (x *CPU) GetRecommendedPower() int32 {
	if x != nil {
		return x.RecommendedPower
	}
	return 0
}

func (x *CPU) GetAvgPrice() float32 {
	if x != nil {
		return x.AvgPrice
	}
	return 0
}

func (x *CPU) GetReleaseDate() *timestamp.Timestamp {
	if x != nil {
		return x.ReleaseDate
	}
	return nil
}

func (x *CPU) GetImg() []byte {
	if x != nil {
		return x.Img
	}
	return nil
}

func (x *CPU) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GPU struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Brand            string                 `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	Family           string                 `protobuf:"bytes,3,opt,name=family,proto3" json:"family,omitempty"`
	Series           string                 `protobuf:"bytes,4,opt,name=series,proto3" json:"series,omitempty"`
	MemoryAmount     int32                  `protobuf:"varint,5,opt,name=memory_amount,json=memoryAmount,proto3" json:"memory_amount,omitempty"`
	MemoryGen        string                 `protobuf:"bytes,6,opt,name=memory_gen,json=memoryGen,proto3" json:"memory_gen,omitempty"`
	Cores            int32                  `protobuf:"varint,7,opt,name=cores,proto3" json:"cores,omitempty"`
	RecommendedPower int32                  `protobuf:"varint,8,opt,name=recommended_power,json=recommendedPower,proto3" json:"recommended_power,omitempty"`
	AvgPrice         float32                `protobuf:"fixed32,9,opt,name=avg_price,json=avgPrice,proto3" json:"avg_price,omitempty"`
	ReleaseDate      *timestamp.Timestamp   `protobuf:"bytes,10,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	Img              []byte                 `protobuf:"bytes,11,opt,name=img,proto3,oneof" json:"img,omitempty"`
	CreatedAt        *timestamp.Timestamp   `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GPU) Reset() {
	*x = GPU{}
	mi := &file_hardwares_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPU) ProtoMessage() {}

func (x *GPU) ProtoReflect() protoreflect.Message {
	mi := &file_hardwares_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPU.ProtoReflect.Descriptor instead.
func (*GPU) Descriptor() ([]byte, []int) {
	return file_hardwares_proto_rawDescGZIP(), []int{1}
}

func (x *GPU) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GPU) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *GPU) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *GPU) GetSeries() string {
	if x != nil {
		return x.Series
	}
	return ""
}

func (x *GPU) GetMemoryAmount() int32 {
	if x != nil {
		return x.MemoryAmount
	}
	return 0
}

func (x *GPU) GetMemoryGen() string {
	if x != nil {
		return x.MemoryGen
	}
	return ""
}

func (x *GPU) GetCores() int32 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *GPU) GetRecommendedPower() int32 {
	if x != nil {
		return x.RecommendedPower
	}
	return 0
}

func (x *GPU) GetAvgPrice() float32 {
	if x != nil {
		return x.AvgPrice
	}
	return 0
}

func (x *GPU) GetReleaseDate() *timestamp.Timestamp {
	if x != nil {
		return x.ReleaseDate
	}
	return nil
}

func (x *GPU) GetImg() []byte {
	if x != nil {
		return x.Img
	}
	return nil
}

func (x *GPU) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type RAM_Memory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Brand         string                 `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	TypeMemory    string                 `protobuf:"bytes,3,opt,name=type_memory,json=typeMemory,proto3" json:"type_memory,omitempty"`
	MemoryAmount  int32                  `protobuf:"varint,4,opt,name=memory_amount,json=memoryAmount,proto3" json:"memory_amount,omitempty"`
	FrequencyMhz  int32                  `protobuf:"varint,5,opt,name=frequency_mhz,json=frequencyMhz,proto3" json:"frequency_mhz,omitempty"`
	Series        string                 `protobuf:"bytes,6,opt,name=series,proto3" json:"series,omitempty"`
	Img           []byte                 `protobuf:"bytes,7,opt,name=img,proto3,oneof" json:"img,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RAM_Memory) Reset() {
	*x = RAM_Memory{}
	mi := &file_hardwares_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAM_Memory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAM_Memory) ProtoMessage() {}

func (x *RAM_Memory) ProtoReflect() protoreflect.Message {
	mi := &file_hardwares_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAM_Memory.ProtoReflect.Descriptor instead.
func (*RAM_Memory) Descriptor() ([]byte, []int) {
	return file_hardwares_proto_rawDescGZIP(), []int{2}
}

func (x *RAM_Memory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RAM_Memory) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *RAM_Memory) GetTypeMemory() string {
	if x != nil {
		return x.TypeMemory
	}
	return ""
}

func (x *RAM_Memory) GetMemoryAmount() int32 {
	if x != nil {
		return x.MemoryAmount
	}
	return 0
}

func (x *RAM_Memory) GetFrequencyMhz() int32 {
	if x != nil {
		return x.FrequencyMhz
	}
	return 0
}

func (x *RAM_Memory) GetSeries() string {
	if x != nil {
		return x.Series
	}
	return ""
}

func (x *RAM_Memory) GetImg() []byte {
	if x != nil {
		return x.Img
	}
	return nil
}

func (x *RAM_Memory) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Mother_Board struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Brand         string                 `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	Series        string                 `protobuf:"bytes,3,opt,name=series,proto3" json:"series,omitempty"`
	Lga           string                 `protobuf:"bytes,4,opt,name=lga,proto3" json:"lga,omitempty"`
	PciExpress    int32                  `protobuf:"varint,5,opt,name=pci_express,json=pciExpress,proto3" json:"pci_express,omitempty"`
	AvgPrice      float32                `protobuf:"fixed32,6,opt,name=avg_price,json=avgPrice,proto3" json:"avg_price,omitempty"`
	Img           []byte                 `protobuf:"bytes,7,opt,name=img,proto3,oneof" json:"img,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mother_Board) Reset() {
	*x = Mother_Board{}
	mi := &file_hardwares_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mother_Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mother_Board) ProtoMessage() {}

func (x *Mother_Board) ProtoReflect() protoreflect.Message {
	mi := &file_hardwares_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mother_Board.ProtoReflect.Descriptor instead.
func (*Mother_Board) Descriptor() ([]byte, []int) {
	return file_hardwares_proto_rawDescGZIP(), []int{3}
}

func (x *Mother_Board) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Mother_Board) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Mother_Board) GetSeries() string {
	if x != nil {
		return x.Series
	}
	return ""
}

func (x *Mother_Board) GetLga() string {
	if x != nil {
		return x.Lga
	}
	return ""
}

func (x *Mother_Board) GetPciExpress() int32 {
	if x != nil {
		return x.PciExpress
	}
	return 0
}

func (x *Mother_Board) GetAvgPrice() float32 {
	if x != nil {
		return x.AvgPrice
	}
	return 0
}

func (x *Mother_Board) GetImg() []byte {
	if x != nil {
		return x.Img
	}
	return nil
}

func (x *Mother_Board) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Power_Source struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Brand          string                 `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	PowerAmount    int32                  `protobuf:"varint,3,opt,name=power_amount,json=powerAmount,proto3" json:"power_amount,omitempty"`
	Ranking        string                 `protobuf:"bytes,4,opt,name=ranking,proto3" json:"ranking,omitempty"`
	EightyPlusCert bool                   `protobuf:"varint,5,opt,name=eighty_plus_cert,json=eightyPlusCert,proto3" json:"eighty_plus_cert,omitempty"`
	AvgPrice       float32                `protobuf:"fixed32,6,opt,name=avg_price,json=avgPrice,proto3" json:"avg_price,omitempty"`
	Img            []byte                 `protobuf:"bytes,7,opt,name=img,proto3,oneof" json:"img,omitempty"`
	CreatedAt      *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Power_Source) Reset() {
	*x = Power_Source{}
	mi := &file_hardwares_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Power_Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Power_Source) ProtoMessage() {}

func (x *Power_Source) ProtoReflect() protoreflect.Message {
	mi := &file_hardwares_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Power_Source.ProtoReflect.Descriptor instead.
func (*Power_Source) Descriptor() ([]byte, []int) {
	return file_hardwares_proto_rawDescGZIP(), []int{4}
}

func (x *Power_Source) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Power_Source) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Power_Source) GetPowerAmount() int32 {
	if x != nil {
		return x.PowerAmount
	}
	return 0
}

func (x *Power_Source) GetRanking() string {
	if x != nil {
		return x.Ranking
	}
	return ""
}

func (x *Power_Source) GetEightyPlusCert() bool {
	if x != nil {
		return x.EightyPlusCert
	}
	return false
}

func (x *Power_Source) GetAvgPrice() float32 {
	if x != nil {
		return x.AvgPrice
	}
	return 0
}

func (x *Power_Source) GetImg() []byte {
	if x != nil {
		return x.Img
	}
	return nil
}

func (x *Power_Source) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_hardwares_proto protoreflect.FileDescriptor

const file_hardwares_proto_rawDesc = "" +
	"\n" +
	"\x0fhardwares.proto\x12\abuilder\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe6\x03\n" +
	"\x03CPU\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05brand\x18\x02 \x01(\tR\x05brand\x12\x10\n" +
	"\x03gen\x18\x03 \x01(\tR\x03gen\x12\x14\n" +
	"\x05cores\x18\x04 \x01(\x05R\x05cores\x12\x18\n" +
	"\athreads\x18\x05 \x01(\x05R\athreads\x12\x1d\n" +
	"\n" +
	"base_clock\x18\x06 \x01(\x02R\tbaseClock\x12\x1b\n" +
	"\tmax_clock\x18\a \x01(\x02R\bmaxClock\x12\x14\n" +
	"\x05cache\x18\b \x01(\x05R\x05cache\x12\x16\n" +
	"\x06socket\x18\t \x01(\tR\x06socket\x12\x1a\n" +
	"\bgraphics\x18\n" +
	" \x01(\bR\bgraphics\x12\x0e\n" +
	"\x02oc\x18\v \x01(\bR\x02oc\x12+\n" +
	"\x11recommended_power\x18\f \x01(\x05R\x10recommendedPower\x12\x1b\n" +
	"\tavg_price\x18\r \x01(\x02R\bavgPrice\x12=\n" +
	"\frelease_date\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\vreleaseDate\x12\x15\n" +
	"\x03img\x18\x0f \x01(\fH\x00R\x03img\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x06\n" +
	"\x04_img\"\x98\x03\n" +
	"\x03GPU\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05brand\x18\x02 \x01(\tR\x05brand\x12\x16\n" +
	"\x06family\x18\x03 \x01(\tR\x06family\x12\x16\n" +
	"\x06series\x18\x04 \x01(\tR\x06series\x12#\n" +
	"\rmemory_amount\x18\x05 \x01(\x05R\fmemoryAmount\x12\x1d\n" +
	"\n" +
	"memory_gen\x18\x06 \x01(\tR\tmemoryGen\x12\x14\n" +
	"\x05cores\x18\a \x01(\x05R\x05cores\x12+\n" +
	"\x11recommended_power\x18\b \x01(\x05R\x10recommendedPower\x12\x1b\n" +
	"\tavg_price\x18\t \x01(\x02R\bavgPrice\x12=\n" +
	"\frelease_date\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vreleaseDate\x12\x15\n" +
	"\x03img\x18\v \x01(\fH\x00R\x03img\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x06\n" +
	"\x04_img\"\x8f\x02\n" +
	"\n" +
	"RAM_Memory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05brand\x18\x02 \x01(\tR\x05brand\x12\x1f\n" +
	"\vtype_memory\x18\x03 \x01(\tR\n" +
	"typeMemory\x12#\n" +
	"\rmemory_amount\x18\x04 \x01(\x05R\fmemoryAmount\x12#\n" +
	"\rfrequency_mhz\x18\x05 \x01(\x05R\ffrequencyMhz\x12\x16\n" +
	"\x06series\x18\x06 \x01(\tR\x06series\x12\x15\n" +
	"\x03img\x18\a \x01(\fH\x00R\x03img\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x06\n" +
	"\x04_img\"\xf6\x01\n" +
	"\fMother_Board\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05brand\x18\x02 \x01(\tR\x05brand\x12\x16\n" +
	"\x06series\x18\x03 \x01(\tR\x06series\x12\x10\n" +
	"\x03lga\x18\x04 \x01(\tR\x03lga\x12\x1f\n" +
	"\vpci_express\x18\x05 \x01(\x05R\n" +
	"pciExpress\x12\x1b\n" +
	"\tavg_price\x18\x06 \x01(\x02R\bavgPrice\x12\x15\n" +
	"\x03img\x18\a \x01(\fH\x00R\x03img\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x06\n" +
	"\x04_img\"\x92\x02\n" +
	"\fPower_Source\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05brand\x18\x02 \x01(\tR\x05brand\x12!\n" +
	"\fpower_amount\x18\x03 \x01(\x05R\vpowerAmount\x12\x18\n" +
	"\aranking\x18\x04 \x01(\tR\aranking\x12(\n" +
	"\x10eighty_plus_cert\x18\x05 \x01(\bR\x0eeightyPlusCert\x12\x1b\n" +
	"\tavg_price\x18\x06 \x01(\x02R\bavgPrice\x12\x15\n" +
	"\x03img\x18\a \x01(\fH\x00R\x03img\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x06\n" +
	"\x04_imgBDZBgithub.com/erickoda/build-a-computer/pc_builder_service/pkg/protosb\x06proto3"

var (
	file_hardwares_proto_rawDescOnce sync.Once
	file_hardwares_proto_rawDescData []byte
)

func file_hardwares_proto_rawDescGZIP() []byte {
	file_hardwares_proto_rawDescOnce.Do(func() {
		file_hardwares_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hardwares_proto_rawDesc), len(file_hardwares_proto_rawDesc)))
	})
	return file_hardwares_proto_rawDescData
}

var file_hardwares_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_hardwares_proto_goTypes = []any{
	(*CPU)(nil),                 // 0: builder.CPU
	(*GPU)(nil),                 // 1: builder.GPU
	(*RAM_Memory)(nil),          // 2: builder.RAM_Memory
	(*Mother_Board)(nil),        // 3: builder.Mother_Board
	(*Power_Source)(nil),        // 4: builder.Power_Source
	(*timestamp.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_hardwares_proto_depIdxs = []int32{
	5, // 0: builder.CPU.release_date:type_name -> google.protobuf.Timestamp
	5, // 1: builder.CPU.created_at:type_name -> google.protobuf.Timestamp
	5, // 2: builder.GPU.release_date:type_name -> google.protobuf.Timestamp
	5, // 3: builder.GPU.created_at:type_name -> google.protobuf.Timestamp
	5, // 4: builder.RAM_Memory.created_at:type_name -> google.protobuf.Timestamp
	5, // 5: builder.Mother_Board.created_at:type_name -> google.protobuf.Timestamp
	5, // 6: builder.Power_Source.created_at:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_hardwares_proto_init() }
func file_hardwares_proto_init() {
	if File_hardwares_proto != nil {
		return
	}
	file_hardwares_proto_msgTypes[0].OneofWrappers = []any{}
	file_hardwares_proto_msgTypes[1].OneofWrappers = []any{}
	file_hardwares_proto_msgTypes[2].OneofWrappers = []any{}
	file_hardwares_proto_msgTypes[3].OneofWrappers = []any{}
	file_hardwares_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hardwares_proto_rawDesc), len(file_hardwares_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hardwares_proto_goTypes,
		DependencyIndexes: file_hardwares_proto_depIdxs,
		MessageInfos:      file_hardwares_proto_msgTypes,
	}.Build()
	File_hardwares_proto = out.File
	file_hardwares_proto_goTypes = nil
	file_hardwares_proto_depIdxs = nil
}
